### ISSUE TITLE
does this support recording the meet?

### ISSUE THREAD

**Issue by ahmad-reza619** [ShaunB56/GoogleMeetAPI#1]
As the title mentioned, i wanted to record the meet for later purpose, can this api does this?

**Comment by shaunbharat** [comment]
Unfortunately, it does not, at the moment. The only exported APIs are the basic ones listed in the README. I'm also not sure if the codebase still works because I haven't tested it since the last release.

I've had plans to come back to this project and rewrite it in TypeScript and add features, but I just haven't had time, so I wouldn't count on it.

If you want to screen record programmatically, this library](https://github.com/muaz-khan/RecordRTC) seems like it could suit your needs, but I haven't looked into it.

**Comment by ahmad-reza619** [comment]
> If you want to screen record programmatically, this library](https://github.com/muaz-khan/RecordRTC) seems like it could suit your needs, but I haven't looked into it.

From what i see this lib only record the screen, i don't know if it's doable in puppeteer. Btw, if u need help migrating to typescript, i could help 😄 . would love to contribute.

I'll close this issue now since i know it isn't supported _yet_. Thanks

**Comment by shaunbharat** [comment]
Thank you for the offer! I'd gladly accept any contributions. I actually started locally experimenting with TypeScript a while ago, and tried to have all the selectors for each element in a single "constants" file, so it would be easier to update the selectors in case Google Meet's UI changed.

However, that was a while ago, and I haven't went back to it since. I also have exams this week. So, if you could do something like that, your contribution would be greatly appreciated!
